### ISSUE TITLE
--lint_out: protoc-gen-lint: Plugin failed with status code 3.

### ISSUE THREAD

**Issue by pawmart** [ckaznocha/protoc-gen-lint#17] opened 2018-09-15 22:17 UTC
I do have some errors listed but final file is not generated for some reason?

**Comment by ckaznocha** [comment] 2018-09-22 01:52
Hey @pawmart, That's actually the intended behavior. The error code (3 in your case) is the number of issues found. An exit code of 0 means it didn't find anything wrong with your protobuf. It doesn't generate any files, in only prints the errors to stderr.

What kind of file would you expect to be generated?

I'll close this one but please to comment about the file, we can spin it off into a new issue :)

**Closed by ckaznocha** 2018-09-22 01:52 UTC
